"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Pre MFP Batch Programs\Clear MFP Libraries.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Intrasectorals.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Nonemployer.sas"
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_ASM Costs.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Cost of Services.sas"
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_All Deflators IO Level.sas"
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Price of Services.sas"
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Price of Materials.sas"
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_IP.sas"