"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Intrasectorals.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Nonemployer.sas"
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_ASM Costs.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Cost of Services.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_IP.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Capital Comp.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Capital Rental Prices.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Capital Index.sas" 
"C:\Program Files\SASHome\SASFoundation\9.4\sas.exe" -sysin "\\filer6\OPT\IT\Prod\DIPStest\SAS Testing\MFP Re-write\Final Programs\Manf_Final MFP.sas" 
